//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_grass_tile2_H
#define METASPRITE_grass_tile2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define grass_tile2_TILE_ORIGIN 0
#define grass_tile2_TILE_W 8
#define grass_tile2_TILE_H 8
#define grass_tile2_WIDTH 16
#define grass_tile2_HEIGHT 16
#define grass_tile2_TILE_COUNT 4
#define grass_tile2_PALETTE_COUNT 1
#define grass_tile2_COLORS_PER_PALETTE 4
#define grass_tile2_TOTAL_COLORS 4
#define grass_tile2_MAP_ATTRIBUTES 0
extern const unsigned char grass_tile2_map[4];
#define grass_tile2_map_attributes grass_tile2_map

BANKREF_EXTERN(grass_tile2)

extern const palette_color_t grass_tile2_palettes[4];
extern const uint8_t grass_tile2_tiles[64];

#endif