//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_grass_tile3_H
#define METASPRITE_grass_tile3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define grass_tile3_TILE_ORIGIN 0
#define grass_tile3_TILE_W 8
#define grass_tile3_TILE_H 8
#define grass_tile3_WIDTH 16
#define grass_tile3_HEIGHT 16
#define grass_tile3_TILE_COUNT 4
#define grass_tile3_PALETTE_COUNT 1
#define grass_tile3_COLORS_PER_PALETTE 4
#define grass_tile3_TOTAL_COLORS 4
#define grass_tile3_MAP_ATTRIBUTES 0
extern const unsigned char grass_tile3_map[4];
#define grass_tile3_map_attributes grass_tile3_map

BANKREF_EXTERN(grass_tile3)

extern const palette_color_t grass_tile3_palettes[4];
extern const uint8_t grass_tile3_tiles[64];

#endif