//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_maincharacter_H
#define METASPRITE_maincharacter_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define maincharacter_TILE_ORIGIN 0
#define maincharacter_TILE_W 8
#define maincharacter_TILE_H 8
#define maincharacter_WIDTH 16
#define maincharacter_HEIGHT 16
#define maincharacter_TILE_COUNT 4
#define maincharacter_PALETTE_COUNT 1
#define maincharacter_COLORS_PER_PALETTE 4
#define maincharacter_TOTAL_COLORS 4
#define maincharacter_MAP_ATTRIBUTES 0
extern const unsigned char maincharacter_map[4];
#define maincharacter_map_attributes maincharacter_map

BANKREF_EXTERN(maincharacter)

extern const palette_color_t maincharacter_palettes[4];
extern const uint8_t maincharacter_tiles[64];

#endif
